name: 'Get latest release'
description: 'Get the latest release of your repository'
inputs:
  token:
    description: 'The Github token.'
    required: false
    default: ${{ github.token }}
  keepv:
    description: 'Keep the v in front of the version.'
    required: false
    default: 'true'
outputs:
  release: # id of output
    description: "The latest release's tag name"
runs:
  using: 'node20'
  main: 'dist/index.js'
