on: [push]

jobs:
  has-tags_job:
    runs-on: ubuntu-latest
    name: Get the latest release
    steps:
      - name: Get the latest release
        id: check
        uses: ahzed11/get-latest-release-action@v1.1
      - name: Echo the latest release
        run: echo "Latest release ${{ steps.check.outputs.release }}"
